### ISSUE TITLE
window.document error when using with "gatsby build"

### ISSUE THREAD

**Issue by GregX999** [ryanvalentin/disqus-react#7]
The line "var DOC = window.document;" causes an error when using this plugin with Gatsby. When you do a "gatsby build" command, Webpack throws the error "WebpackError: window is not defined". From when I could figure out, I think the reference to window.document needs to be moved into the componentDidMount method (by which time window would exist).

See: https://www.gatsbyjs.org/docs/debugging-html-builds/

**Comment by ryanvalentin** [comment]
This should be easy enough to fix, and would benefit any server-side rendering

**Comment by mernflow** [comment]
still breaking as of April 12, 2019 using GatsbyJS and Netlify see error below

**ERROR**
failed during stage 'building site': Build script returned non-zero exit code: 1

this is caused by same issue site builds fine without this package but as soon as i add it site breaks

also i can run / build on local env but when i move to build in production i get that error
